name: Frisco Financial Planning LLC Blog
favicon: null
layout_spectrum: 0.75661
typography_spectrum: 0.6268
title: Frisco Financial Planning LLC Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e3d8'
    - '#000000'
    - '#7a7a7a'
    - '#733639'
    - '#c3b29a'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
